---
language: php
php: stable
env:
  global:
  # ================= App settings =================
  # your environment variables
  # ========== Heroku Pipelines for Travis =========
  # -------------------- Deploy --------------------
  - HP4T_DEPLOY_FROM_REPOSITORY=repo/name
  - HP4T_DEPLOY_FROM_BRANCH=master
  # ----------------- Heroku apps ------------------
  - HP4T_HEROKU_APPNAME_STAGE=app-name-stage
  - HP4T_HEROKU_APPNAME_PRODUCTION=CHANGE_ME_app-name-prod
  # ------------ Additional sesstings --------------
  # HP4T_ROLLBAR_DEPLOY_KEY
  - secure: ""
  # HEROKU_API_KEY
  - secure: ""
cache:
  directories:
  - vendor
before_install:
- nvm stable
- alias hp4t="$(npm bin)/hp4t"
install:
- composer install
before_script:
- composer test
- hp4t init
- hp4t provision stage
- hp4t deploy $HP4T_HEROKU_APPNAME_STAGE
# - hp4t run $HP4T_HEROKU_APPNAME_STAGE "composer migrate-database"
- hp4t provision production
- hp4t promote $HP4T_HEROKU_APPNAME_STAGE
# - hp4t run $HP4T_HEROKU_APPNAME_PRODUCTION "composer migrate-database"
script:
- /bin/true
after_success:
- hp4t notify-rollbar
