language: php
php: 7.0
env:
  global:
  - HEROKU_API_KEY
  - HP4T_ROLLBAR_DEPLOY_KEY
  # ==================== Deploy ====================
  - HP4T_DEPLOY_FROM_REPOSITORY=bergens-tidende/perks-royal
  - HP4T_DEPLOY_FROM_BRANCH=master
  # ==================== Heroku app ====================
  - HP4T_HEROKU_APPNAME_STAGE=perks-api-stage
  - HP4T_HEROKU_APPNAME_PRODUCTION=perks-api
cache:
  directories:
  - vendor
before_install:
- scripts/pipelines4travis/init.sh
- scripts/pipelines4travis/update-nodejs.sh
install:
- composer install
before_script:
- composer test
- scripts/hp4t/heroku/provision.sh stage
- scripts/hp4t/heroku/deploy.sh
- scripts/hp4t/heroku/migrate-database.sh $HEROKU_APPNAME_STAGE
- scripts/hp4t/heroku/provision.sh production
- scripts/hp4t/heroku/promote.sh
- scripts/hp4t/heroku/migrate-database.sh $HEROKU_APPNAME_PRODUCTION
script:
- /bin/true
after_success:
- scripts/hp4t/notifications/rollbar.sh
- scripts/hp4t/notifications/slack.sh
