language: php
php: 7.0
addons:
  apt:
    sources:
     - heroku
    packages:
     - heroku-toolbelt
env:
  global:
  # ================= App settings =================
  # your environment variables
  # ========== Heroku Pipelines for Travis =========
  # -------------------- Deploy --------------------
  - HP4T_DEPLOY_FROM_REPOSITORY=__HP4T_DEPLOY_FROM_REPOSITORY__
  - HP4T_DEPLOY_FROM_BRANCH=__HP4T_DEPLOY_FROM_BRANCH__
  # ----------------- Heroku apps ------------------
  - HP4T_HEROKU_APPNAME_STAGE=__HP4T_HEROKU_APPNAME_STAGE__
  - HP4T_HEROKU_APPNAME_PRODUCTION=__HP4T_HEROKU_APPNAME_PRODUCTION__
  # ------------ Additional sesstings --------------
  # HP4T_ROLLBAR_DEPLOY_KEY
  - secure: __HP4T_ROLLBAR_DEPLOY_KEY__
  # HEROKU_API_KEY
  - secure: __HEROKU_API_KEY__
cache:
  apt: true
  directories:
  - vendor/
install:
- composer install
- alias hp4t="$(npm bin)/hp4t"
before_script:
- composer test
- hp4t init
- hp4t provision stage
- hp4t deploy $HP4T_HEROKU_APPNAME_STAGE
# - hp4t run $HP4T_HEROKU_APPNAME_STAGE "npm run migrate-database"
- hp4t provision production
- hp4t promote $HP4T_HEROKU_APPNAME_STAGE
# - hp4t run $HP4T_HEROKU_APPNAME_PRODUCTION "npm run migrate-database"
script:
- /bin/true
after_success:
- hp4t notify-rollbar
