language: node_js
node_js:
- '4.2.2'
env:
  global:
  # ========== Heroku Pipelines for Travis =========
  # -------------------- Deploy --------------------
  - HP4T_DEPLOY_FROM_REPOSITORY=$DEPLOY_FROM_REPOSITORY
  - HP4T_DEPLOY_FROM_BRANCH=$DEPLOY_FROM_BRANCH
  # ----------------- Heroku apps ------------------
  - HP4T_HEROKU_APPNAME_STAGE=$HEROKU_APPNAME_STAGE
  - HP4T_HEROKU_APPNAME_PRODUCTION=$HEROKU_APPNAME_PRODUCTION
cache:
  directories:
  - node_modules
before_install:
- node_modules/.bin/hp4t/init.sh
install:
- npm install
before_script:
- npm test
- node_modules/.bin/hp4t/provision stage
- node_modules/.bin/hp4t/deploy
- node_modules/.bin/hp4t/migrate-database $HEROKU_APPNAME_STAGE
- node_modules/.bin/hp4t/provision production
- node_modules/.bin/hp4t/promote
- node_modules/.bin/hp4t/migrate-database $HEROKU_APPNAME_PRODUCTION
script:
- /bin/true
after_success:
- scripts/hp4t/notifications/rollbar.sh
- scripts/hp4t/notifications/slack.sh
